#!/bin/bash

echo " "
echo "running miniFE tests..."

if [ ! -x miniFE.x ]; then
echo "miniFE.x doesn't exist or isn't executable. Aborting."
exit -1
fi

./run_one_test 15 1 1 2
if [ $? != 0 ]; then
echo "test failed"
exit $?
fi

./run_one_test 30 1 1 2
if [ $? != 0 ]; then
echo "test failed"
exit $?
fi

./run_one_test 45 1 1 2
if [ $? != 0 ]; then
echo "test failed"
exit $?
fi

./run_one_test 60 1 1 2
if [ $? != 0 ]; then
echo "test failed"
exit $?
fi

./run_one_test 75 1 1 2
if [ $? != 0 ]; then
echo "test failed"
exit $?
fi

./run_one_test 90 1 1 2
if [ $? != 0 ]; then
echo "test failed"
exit $?
fi

./run_one_test 105 1 1 2
if [ $? != 0 ]; then
echo "test failed"
exit $?
fi

./run_one_test 120 1 1 2
if [ $? != 0 ]; then
echo "test failed"
exit $?
fi

